//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF.Tryer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TryerEntities : DbContext
    {
        public TryerEntities()
            : base("name=TryerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sys_Func> Sys_Func { get; set; }
        public virtual DbSet<Sys_Page> Sys_Page { get; set; }
        public virtual DbSet<Sys_PageControl> Sys_PageControl { get; set; }
        public virtual DbSet<Sys_Permission> Sys_Permission { get; set; }
        public virtual DbSet<Sys_Permission_R_Page> Sys_Permission_R_Page { get; set; }
        public virtual DbSet<Sys_Permission_R_PageControl> Sys_Permission_R_PageControl { get; set; }
        public virtual DbSet<Sys_Permission_R_Role> Sys_Permission_R_Role { get; set; }
        public virtual DbSet<Sys_Role> Sys_Role { get; set; }
        public virtual DbSet<Sys_User> Sys_User { get; set; }
        public virtual DbSet<Sys_User_R_Role> Sys_User_R_Role { get; set; }
    }
}
